# Generated by Django 5.0.1 on 2024-02-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_product_cartorderitem_course_coupon_coursefaq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
