# Generated by Django 5.0.1 on 2024-02-21 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_cart_course_cart_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='course',
        ),
        migrations.AddField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='store.course'),
            preserve_default=False,
        ),
    ]
