# Generated by Django 5.0.1 on 2024-02-21 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_cart_course_cart_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.course'),
        ),
    ]
