# Generated by Django 5.0.1 on 2024-02-22 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_cart_course_remove_cart_price_remove_cart_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.cart'),
        ),
    ]
