# Generated by Django 5.0.1 on 2024-02-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cartorder_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='province',
            new_name='country',
        ),
    ]
