# Generated by Django 5.0.1 on 2024-02-23 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_province_cartorder_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cartitem'),
        ),
    ]
