# Generated by Django 5.0.1 on 2024-02-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cartorder_vendor_remove_cartorder_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='cart_item',
            field=models.ManyToManyField(blank=True, to='store.cartitem'),
        ),
    ]
