# Generated by Django 5.0.1 on 2024-02-24 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_cartorder_vendor'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
