# Generated by Django 5.0.1 on 2024-02-24 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_cartitem_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cartitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
    ]
