# Generated by Django 5.0.1 on 2024-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oneTimePassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
